const crypto = require('crypto');
const router = require('express').Router();
const { supabase, createAuthedClient } = require('../utils/db');
const { authMiddleware, hasPermission } = require('../middleware/auth');
const { notify } = require('../utils/notify');
function client(req) { return createAuthedClient(req.headers.authorization?.replace('Bearer ', '')); }
function canManage(req) { return req.user?.role === 'admin' || req.user?.role === 'logistics_operator' || hasPermission(req, 'manage_logistics'); }
async function event(c, shipment, { status, location, description, source, provider_event_id, actorId }) {
  if (!status) throw new Error('A tracking status is required.');
  const { data, error } = await c.from('tracking_events').insert({ shipment_id: shipment.id, status, location: location || null, description: description || null, source, provider_event_id: provider_event_id || null, actor_id: actorId || null }).select().single();
  if (error?.code === '23505') return { duplicate: true }; if (error) throw error;
  const shipped = ['DISPATCHED','PICKED_UP','IN_TRANSIT','OUT_FOR_DELIVERY'].includes(status);
  const delivered = status === 'DELIVERED';
  await c.from('shipments').update({ status, current_location: location || shipment.current_location, dispatched_at: shipped ? shipment.dispatched_at || new Date().toISOString() : shipment.dispatched_at, delivered_at: delivered ? new Date().toISOString() : shipment.delivered_at, updated_at: new Date().toISOString() }).eq('id', shipment.id);
  if (delivered) await c.from('product_orders').update({ status: 'BUYER_CONFIRMATION_PENDING', order_state: 'BUYER_CONFIRMATION_PENDING', updated_at: new Date().toISOString() }).eq('id', shipment.order_id);
  else if (status === 'DISPATCHED') await c.from('product_orders').update({ status: 'DISPATCHED', order_state: 'DISPATCHED', updated_at: new Date().toISOString() }).eq('id', shipment.order_id);
  else if (shipped) await c.from('product_orders').update({ status: status === 'OUT_FOR_DELIVERY' ? 'OUT_FOR_DELIVERY' : 'IN_TRANSIT', order_state: status === 'OUT_FOR_DELIVERY' ? 'OUT_FOR_DELIVERY' : 'IN_TRANSIT', updated_at: new Date().toISOString() }).eq('id', shipment.order_id);
  await c.from('product_transaction_audit').insert({ order_id: shipment.order_id, shipment_id: shipment.id, actor_id: actorId || null, action: 'tracking_event_recorded', next_value: { status, location: location || null, source }, reason: description || null });
  const { data: order } = await c.from('product_orders').select('buyer_id,seller_id,order_code').eq('id', shipment.order_id).maybeSingle();
  if (order) for (const userId of [order.buyer_id, order.seller_id]) await notify(c, { userId, type: 'shipment_update', title: `Shipment ${status.replaceAll('_',' ')}`, body: `Order ${order.order_code}: ${location || status}.`, link: `/tracking.html?shipment=${shipment.id}` });
  return data;
}

router.use(authMiddleware);
router.get('/providers', async (req, res) => { if (!canManage(req)) return res.status(403).json({ error: 'Logistics access required.' }); const { data, error } = await client(req).from('logistics_providers').select('id,provider_code,company_name,contact_name,contact_email,contact_phone,api_base_url,api_config,webhook_secret_hint,supported_locations,supported_services,integration_mode,is_active,created_at,updated_at').order('company_name'); if (error) return res.status(400).json({ error: error.message }); res.json(data || []); });
router.post('/providers', async (req, res) => { if (req.user.role !== 'admin') return res.status(403).json({ error: 'Administrator access required.' }); const b = req.body || {}; if (!b.company_name || !b.provider_code) return res.status(400).json({ error: 'Provider name and code are required.' }); const safe = { provider_code: String(b.provider_code).toUpperCase().replace(/[^A-Z0-9_]/g, '_'), company_name: b.company_name, contact_name: b.contact_name || null, contact_email: b.contact_email || null, contact_phone: b.contact_phone || null, api_base_url: b.api_base_url || null, api_config: b.api_config || {}, webhook_secret_hint: b.webhook_secret_hint || null, supported_locations: b.supported_locations || [], supported_services: b.supported_services || [], integration_mode: b.integration_mode === 'api' ? 'api' : 'manual', is_active: b.is_active !== false }; const { data, error } = await client(req).from('logistics_providers').insert(safe).select().single(); if (error) return res.status(400).json({ error: error.message }); res.status(201).json(data); });
router.put('/providers/:id', async (req, res) => { if (req.user.role !== 'admin') return res.status(403).json({ error: 'Administrator access required.' }); const allowed = ['company_name','contact_name','contact_email','contact_phone','api_base_url','api_config','webhook_secret_hint','supported_locations','supported_services','integration_mode','is_active']; const patch = Object.fromEntries(Object.entries(req.body || {}).filter(([key]) => allowed.includes(key))); patch.updated_at = new Date().toISOString(); const { data, error } = await client(req).from('logistics_providers').update(patch).eq('id', req.params.id).select().single(); if (error) return res.status(400).json({ error: error.message }); res.json(data); });
router.delete('/providers/:id', async (req, res) => { if (req.user.role !== 'admin') return res.status(403).json({ error: 'Administrator access required.' }); const { count } = await client(req).from('shipments').select('id', { count: 'exact', head: true }).eq('provider_id', req.params.id); if (count) return res.status(400).json({ error: 'This provider has shipments and cannot be removed. Deactivate it instead.' }); const { error } = await client(req).from('logistics_providers').delete().eq('id', req.params.id); if (error) return res.status(400).json({ error: error.message }); res.json({ ok: true }); });
router.post('/shipments', async (req, res) => { const c = client(req), b = req.body || {}; const { data: order } = await c.from('product_orders').select('*').eq('id', b.order_id).maybeSingle(); if (!order || (order.seller_id !== req.user.id && !canManage(req))) return res.status(404).json({ error: 'Order not found.' }); if (order.status !== 'READY_FOR_DISPATCH' && !canManage(req)) return res.status(400).json({ error: 'Buyer approval is required before dispatch.' }); const { data, error } = await c.from('shipments').insert({ shipment_code: `SHP-${Date.now().toString().slice(-8)}`, order_id: order.id, provider_id: b.provider_id || null, tracking_number: b.tracking_number || null, dispatch_method: b.dispatch_method || 'manual', dispatch_details: b.dispatch_details || {}, dispatch_images: b.dispatch_images || [], estimated_delivery_at: b.estimated_delivery_at || null, created_by: req.user.id, status: 'DISPATCHED', dispatched_at: new Date().toISOString() }).select().single(); if (error) return res.status(400).json({ error: error.message }); await event(c, data, { status: 'DISPATCHED', location: b.pickup_location || null, description: b.description || 'Seller submitted dispatch.', source: 'manual', actorId: req.user.id }); res.status(201).json(data); });
router.post('/shipments/:id/events', async (req, res) => { const c = client(req); const { data: shipment } = await c.from('shipments').select('*, product_orders(seller_id)').eq('id', req.params.id).maybeSingle(); if (!shipment || (shipment.product_orders?.seller_id !== req.user.id && !canManage(req))) return res.status(404).json({ error: 'Shipment not found.' }); try { res.status(201).json(await event(c, shipment, { ...(req.body || {}), source: canManage(req) ? 'admin' : 'manual', actorId: req.user.id })); } catch (e) { res.status(400).json({ error: e.message }); } });
router.get('/shipments/:id', async (req, res) => { const c = client(req); const { data, error } = await c.from('shipments').select('*, logistics_providers(id,company_name), tracking_events(*)').eq('id', req.params.id).maybeSingle(); if (error || !data) return res.status(404).json({ error: 'Shipment not found.' }); const { data: order } = await c.from('product_orders').select('buyer_id,seller_id').eq('id', data.order_id).maybeSingle(); if (!order || (![order.buyer_id, order.seller_id].includes(req.user.id) && !canManage(req))) return res.status(404).json({ error: 'Shipment not found.' }); data.tracking_events = (data.tracking_events || []).sort((a,b) => new Date(a.event_at) - new Date(b.event_at)); res.json(data); });
module.exports = router;
